### ISSUE TITLE
issue #9

### ISSUE THREAD

**Issue by lbb00** [echotechfe/weekly#3]

**Comment by lbb00** [comment]
https://blog.val.town/blog/first-four-val-town-runtimes  val town 目前的 JavaScript 运行时进化史

**Comment by GideonSenku** [comment]
书籍推荐：《深度工作》（deep work）

**Comment by zhuscat** [comment]
https://rolldown.rs/

Rolldown

**Comment by lbb00** [comment]
> 书籍推荐：《深度工作》（deep work）

书籍类的推荐还是写上摘要吧，毕竟我没看过，不知道如何下笔。
