### ISSUE TITLE
第 10 期投稿收集

### ISSUE THREAD

**Issue by lbb00** [echotechfe/weekly#4]

**Comment by lbb00** [comment]
https://mp.weixin.qq.com/s/NLkeTDFCUqw_2bV2a_V0wA

Qwik 框架旨在只在需要时加载必要的 JavaScript，比 React 基于路由加载 JavaScript 的颗粒度更小，从而优化性能和用户体验。

**Comment by zhuscat** [comment]
https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/

Node 要支持用 require 的方式引入 ESM 了

模块的格式在 JS 生态仍然是个令人烦恼的问题，比如之前允许 ESM 引入 CJS，但不支持 CJS 引入 ESM

然后生态内也比较割裂，比如一些包只有 ESM 产物，一些包则保证最大兼容性（编译各种产物）
