### ISSUE TITLE
第 11 期投稿收集

### ISSUE THREAD

**Issue by lbb00** [EchoTechFE/weekly#5]
RT.

**Comment by zhuscat** [comment]
https://www.alibabacloud.com/help/zh/cdn/product-overview/configure-high-bill-alerts

这周我们的 CDN 被盗刷流量了，大概是对方向 OSS 上传了视频分片文件，用我们的 CDN 流量给用户播放视频

这里可以看看如何尽量减少 CDN 被盗流的风险
